# Generated by Django 3.1.6 on 2021-04-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votepage', '1_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('selection', models.CharField(max_length=100)),
            ],
        ),
    ]
