# Generated by Django 3.1.6 on 2021-04-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votepage', '0002_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
