# Generated by Django 3.1.6 on 2021-04-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votepage', '0003_auto_20210418_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive',
            name='DOB',
        ),
    ]
