# Generated by Django 3.1.6 on 2021-04-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votepage', '0006_auto_20210418_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='received_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
