# Generated by Django 3.1.6 on 2021-04-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votepage', '0007_auto_20210418_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='mail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
