# Generated by Django 3.1.6 on 2021-04-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='voteoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('reg_no', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('year_of_study', models.PositiveIntegerField()),
                ('course_and_dept', models.CharField(max_length=100)),
            ],
        ),
    ]
